.TH "TTAB" "1" "March 2017" "v0.5.1" ""
.SH "NAME"
\fBttab\fR \- open a new Terminal\.app / iTerm\.app tab or window
.SH SYNOPSIS
.P
Opens a new terminal tab or window in OS X's Terminal application or iTerm2\.
.P
.RS 2
.nf
ttab [\-w] [\-s <settings>] [\-t <title>] [\-q] [\-g|\-G] [\-d <dir>] [<cmd> \.\.\.]

\-w                  open new tab in new terminal window
\-s <settings>       assign a settings set (profile)
\-t <title>          specify title for new tab
\-q                  clear the new tab's screen
\-g                  create tab in background (don't activate Terminal/iTerm)
\-G                  create tab in background and don't activate new tab
\-d <dir>            specify working directory
\-a Terminal|iTerm2  open tab or window in Terminal\.app / iTerm2  
<cmd> \.\.\.           command to execute in the new tab
"<cmd> \.\.\.; \.\.\."    multi\-command command line (passed as single operand)
.fi
.RE
.P
Standard options: \fB\-\-help\fP, \fB\-\-man\fP, \fB\-\-version\fP, \fB\-\-home\fP
.SH DESCRIPTION
.P
\fBttab\fP opens a new Terminal or iTerm2 tab with a variety of options,
.br
including executing a command in the new tab, assigning a title and working
.br
directory, and opening the tab in a new window\.
.P
Note: iTerm2 support is experimental in that it is currently not covered by
.br
the automated tests run before every release\.
.P
IMPORTANT: \fBTerminal/iTerm2 must be allowed assistive access\fR in order
.br
for this  utility to work, which requires one\-time authorization with
.br
administrative privileges\. If you get error messages instead of being prompted,
.br
authorize the application via
.br
System Preferences > Security & Privacy > Privacy > Accessibility\.
.P
The new tab will run a login shell (i\.e\., load the user's shell profile)
.br
and by default inherit the working directory from the parent shell\.
.P
When specifying a command to execute in the new tab, quoted parameters are
.br
handled properly and there's no need to quote the command as a whole,
.br
provided it is a \fIsingle\fR command\.
.br
Prefix such a single command with \fBexec\fP to exit the shell after the command
.br
terminates\. If the tab's settings are configured to close tabs on termination
.br
of the shell, the tab will close automatically\.
.P
To specify \fImultiple\fR commands, pass them as a \fIsingle, quoted  string\fR\|\.
.br
Use \fBexit\fP as the last command to automatically close the tab when the
.br
command terminates, assuming the tab's settings are configured to close the
.br
tab on termination of the shell\.
.br
Precede \fBexit\fP with \fBread \-rsn 1\fP to wait for a keystroke first\.
.SH OPTIONS
.RS 0
.IP \(bu 2
\fB\-w\fP
.br
 creates the new tab in a new window rather than in the front
.br
 window\.
.IP \(bu 2
\fB\-s <settings>\fP
.br
 specifies the settings set (profile) to apply to the new tab, determining
.br
 the appearance and behavior of the new tab\.
.br
 o Terminal: settings sets are defined in Preferences > Profiles;
.br
 name matching is case\-\fIin\fRsensitive, and specifying nonexistent settings
.br
 causes an error\.
 o iTerm2: profiles are defined in Preferences > Profiles; name matching
.br
 is case\-\fIsensitive\fR, and specifying a nonexistent profile causes an error\.
.IP \(bu 2
\fB\-t <title>\fP
.br
 specifies a custom title to assign to the new tab; otherwise, if a
.br
 command is specified, its first token will become the new tab's title\.
.br
 CAVEAT: As of iTerm2 v3\.0\.9, choosing a title that exactly matches the
.br
 settings name specified with \fB\-s\fP causes the title to be ignored\.
.IP \(bu 2
\fB\-d <dir>\fP
.br
 explicitly specifies a working directory for the new tab; by default, the
.br
 invoking shell's working directory is inherited (even if \fB\-w\fP is also
.br
 specified)\.
.IP \(bu 2
\fB\-q\fP
.br
 (\fIq\fRuiet) issues a \fBclear\fP command after opening the new tab\.
.br
 Note that output will temporarily be visible while the tab is being opened;
.br
 also, clearing is not performed if any command passed reports an overall
.br
 nonzero exit code, so as to allow failures to be examined\.
.IP \(bu 2
\fB\-g\fP
.br
 (back\fIg\fRround) causes Terminal/iTerm2 not to activate, if it isn't the
.br
 frontmost application); within the application, however, the new tab will
.br
 become the active tab; useful in scripts that launch other applications and
.br
 don't want Terminal/iTerm2 to steal focus later\.
.IP \(bu 2
\fB\-G\fP
.br
 causes Terminal/iTerm2 not to activate \fIand\fR the active element within
.br
 the application not to change; i\.e\., the active window and tab stay the
.br
 same\. If Terminal/iTerm2 happens to be frontmost, the new tab will
.br
 effectively open in the background\.

.RE
.P
NOTE: With \fB\-g\fP or \fB\-G\fP specified, for technical reasons, Terminal/iTerm2 /
.br
      the new tab will still activate \fIbriefly, temporarily\fR in most scenarios\.
.RS 0
.IP \(bu 2
\fB\-a Terminal\fP or \fB\-a iTerm2\fP
.br
  explicitly specifies the terminal application to use; by default, the
.br
  terminal application from which this utility is run is implied, if
.br
  supported, with Terminal used as the fallback\.
.br
  This options is useful for calling this utility from non\-terminal
.br
  applications such as Alfred (https://www\.alfredapp\.com/)\.

.RE
.SH STANDARD OPTIONS
.P
All standard options provide information only\.
.RS 0
.IP \(bu 2
\fB\-h, \-\-help\fP
.br
 Prints the contents of the synopsis chapter to stdout for quick reference\.
.IP \(bu 2
\fB\-\-man\fP
.br
 Displays this manual page, which is a helpful alternative to using \fBman\fP, 
 if the manual page isn't installed\.
.IP \(bu 2
\fB\-\-version\fP
.br
 Prints version information\.
.IP \(bu 2
\fB\-\-home\fP
.br
 Opens this utility's home page in the system's default web browser\.

.RE
.SH LICENSE
.P
For license information and more, visit this utility's home page by running
.br
\fBttab \-\-home\fP\|\.
.SH EXAMPLES
.P
.RS 2
.nf
# Open new tab in current terminal window:
ttab

# Open new tab in new terminal window:
ttab \-w

# Open new tab with title 'Green' using settings (profile) 'Grass':
ttab \-t Green \-s Grass  

# Open new tab and execute a command in it:
ttab ls \-l "$HOME/Library/Application Support"

# Open new tab with specified working dir\. and execute a command in it:
ttab \-d "$HOME/Library/Application Support" ls \-l

# Execute a command and exit\.
# If configured via the default profile, also close the tab\.
ttab exec /path/to/someprogram arg1 arg2

# Pass a multi\-command string as a single, quoted string, wait for a  
# keystroke, then exit\.
ttab 'ls "$HOME/Library/Application Support";
                            echo Press any key to exit; read \-rsn 1; exit'

# Create a new tab explicitly in iTerm2\.
ttab \-a iTerm2 echo "Hi from iTerm2\."
.fi
.RE

