#!/usr/bin/env osascript

set ttabBin to "../bin/ttab"

# Load the utility script.
set util to load script (do shell script "dirname -- " & quoted form of POSIX path of (path to me)) & "/.fixtures/utils.scpt"

tell application "Terminal"
  
  delay 2 # !! unfortunately, it can take a bit before the window count catches up from the previous test.
    
  set winCountBefore to count of windows

  # Create tab in new window.
  do shell script ttabBin & " -w"

  if not (count of windows) > winCountBefore then error "Failed to create new window."

  # Close the new window, but we must wait for its shell to no longer be busy so as to avoid a 'really close?' prompt.
  util's closeTerminalWindow(front window, 3)

end tell

return

