#!/usr/bin/env osascript

set ttabBin to "../bin/ttab"

# Load the utility script.
set util to load script (do shell script "dirname -- " & quoted form of POSIX path of (path to me)) & "/.fixtures/utils.scpt"

# 1st test: create tab in *front* window and ensure that Terminal doesn't activate (technically: stay activated) in the process.
tell application "Terminal"'s front window
    
  set tabCountBefore to util's getTabCount()
  set thisTab to util's getActiveTab()

  util's syncActivate("Finder")

  # Create tab without activating Terminal.
  do shell script ttabBin & " -g"

  if not (util's getTabCount()) > tabCountBefore then error "Failed to create tab in front window."

  # Tabs don't understand `close`, but `do script "exit"` is preferable anyway (assuming the settings close the tab once the shell exits),
  # because it waits for the tab to be ready to process the command.
  do script "exit" in util's getActiveTab()

  delay 1 # give some time for the required temporary activation of Terminal to pass
  set ok to not frontmost of application "Terminal"

  util's setActiveTab(thisTab) # Re-select the previously active tab

  if not ok then
    activate application "Terminal"
    error "Terminal unexpectedly remained the frontmost application."
  end if

end tell

# 2nd test: create tab in *new* window and ensure that Terminal doesn't activate (technically: stay activated) in the process.
tell application "Terminal"
    
  set winCountBefore to count of windows

  util's syncActivate("Finder")

  # Create tab in a new window without activating Terminal.
  do shell script ttabBin & " -w -g"

  if not (count of windows) > winCountBefore then error "Failed to create new Terminal window."

  delay 1 # give some time for the required temporary activation of Terminal to pass
  set ok to not frontmost of application "Terminal"

  # Close the new window, but we must wait for its shell to no longer be busy so as to avoid a 'really close?' prompt.
  activate it
  util's closeTerminalWindow(front window, 3)

  if not ok then
    activate application "Terminal"
    error "Terminal unexpectedly stayed the frontmost application."
  end if

end tell

return
