#!/usr/bin/env bash

ttabBin="../bin/ttab"

[[ -d /Applications/iTerm.app ]] || { echo "WARNING: Cannot test option -a, because iTerm2 appears not to be installed." >&2; exit 0; }

activateTerminal() {
  osascript -e 'tell application "Terminal.app" to activate'
}

activeiTermSync() {
  osascript -e'
    tell application "iTerm" 
      activate
      repeat until frontmost
        delay 0.1
      end repeat
    end tell
  '
}

# Make sure that iTerm is launched and activated, so that if we can get a reliable
# current window count below.
# If iTerm isn't running and is launched asynchronously, on demand, it initially
# reports 0 windows, before it automatically opens its default window.
activeiTermSync 

numWinsBefore=$(osascript -e 'tell application "iTerm.app" to count windows')

"$ttabBin" -a iTerm2 -w echo "Hi!"

numWinsAfter=$(osascript -e 'tell application "iTerm.app" to count windows')

(( numWinsAfter == numWinsBefore + 1 )) || { echo "Expected to find $(( numWinsBefore + 1 )) windows, but found $numWinsAfter" >&2; activateTerminal; exit 1; }

# Close the newly created iTerm.app window...
osascript -e 'tell application "iTerm.app" to close front window'

# ... and reativate Terminal.app.
activateTerminal

exit 0
